---------------------------------------------------------------
---------- PROJECT 3 SQL-DATA-ANALYSIS DECODELABS -------------
---------------------------------------------------------------


SELECT table_name
FROM user_tables;

SELECT COUNT(*)
FROM ORDERS;

DESC ORDERS;

-- View all data --
SELECT *
FROM ORDERS;

-- Count total orders --
SELECT COUNT(*) AS Total_Orders
FROM ORDERS;

-- Total Revenue --
SELECT SUM(TotalPrice) AS Total_Revenue
FROM ORDERS;

-- Average order value --
SELECT AVG(TOTALPRICE) AS AVG_ORDER_VALUE
FROM ORDERS;

-- Orders above 2000 --
SELECT ORDERID, PRODUCT, TOTALPRICE
FROM ORDERS
WHERE TOTALPRICE > 2000;

-- Delivered orders --
SELECT *
FROM ORDERS
WHERE ORDERSTATUS = 'Delivered';

-- Sort by highest price --
SELECT ORDERID, PRODUCT, TOTALPRICE
FROM ORDERS
ORDER BY TOTALPRICE ASC;

-- Sort by lowest price --
SELECT ORDERID, PRODUCT, TOTALPRICE
FROM ORDERS
ORDER BY TOTALPRICE DESC;

-- Orders by product -- 
SELECT PRODUCT,
       COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY PRODUCT
ORDER BY TOTAL_ORDERS DESC;

-- Revenue by product --
SELECT PRODUCT,
       SUM(TOTALPRICE) AS REVENUE
FROM ORDERS
GROUP BY PRODUCT
ORDER BY REVENUE DESC;

-- Average revenue by product --
SELECT PRODUCT,
       AVG(TOTALPRICE) AS AVG_REVENUE
FROM ORDERS
GROUP BY PRODUCT
ORDER BY AVG_REVENUE DESC;

-- Orders by payment method -- 
SELECT PAYMENTMETHOD,
       COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY PAYMENTMETHOD
ORDER BY TOTAL_ORDERS DESC;

-- Orders by status --
SELECT ORDERSTATUS,
       COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY ORDERSTATUS
ORDER BY TOTAL_ORDERS DESC;

-- Revenue by Referral Source --
SELECT REFERRALSOURCE,
       SUM(TOTALPRICE) AS REVENUE
FROM ORDERS
GROUP BY REFERRALSOURCE
ORDER BY REVENUE DESC;

-- Coupon Usage --
SELECT COUPONCODE,
       COUNT(*) AS TIMES_USED
FROM ORDERS
GROUP BY COUPONCODE
ORDER BY TIMES_USED DESC;

-- Customers spending more than 5000 --
SELECT CUSTOMERID,
       SUM(TOTALPRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY CUSTOMERID
HAVING SUM(TOTALPRICE) > 5000;

-- Top 10 highest revenue orders --
SELECT *
FROM (
    SELECT ORDERID,
           PRODUCT,
           TOTALPRICE
    FROM ORDERS
    ORDER BY TOTALPRICE DESC
)
WHERE ROWNUM <= 10;

-- Total quantity sold by product -- 
SELECT PRODUCT,
       SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM ORDERS
GROUP BY PRODUCT
ORDER BY TOTAL_QUANTITY_SOLD DESC;

-- Top 10 highest spending customers --
SELECT *
FROM (
    SELECT CUSTOMERID,
           SUM(TOTALPRICE) AS TOTAL_SPENT
    FROM ORDERS
    GROUP BY CUSTOMERID
    ORDER BY TOTAL_SPENT DESC
)
WHERE ROWNUM <= 10;

-- Orders with coupons --
SELECT *
FROM ORDERS
WHERE COUPONCODE IS NOT NULL;
